import React,{useState} from 'react';
import {ArrowLeft,Check,ChevronRight,Loader2} from 'lucide-react';
import {signUp} from '../lib/auth';
import './SignupPage.css';

export default function SignupPage(){
 const [name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[message,setMessage]=useState(''),[working,setWorking]=useState(false);
 const submit=async event=>{event.preventDefault();if(password.length<8){setMessage('Use at least 8 characters for your password.');return}if(password!==confirm){setMessage('Passwords do not match.');return}setWorking(true);setMessage('Creating your visitor account…');try{const result=await signUp(email,password,name);if(result.error)throw result.error;setMessage(result.data?.session?'Account created. You can now browse the archive.':'Account created. Check your inbox if email confirmation is required.')}catch(error){setMessage(error.message||'Unable to create your account.')}finally{setWorking(false)}};
 return <main className="signup-page"><a className="signup-back" href="/"><ArrowLeft/> RETURN TO THE ARCHIVE</a><div className="signup-frame"><div className="signup-mark">Z</div><p className="signup-kicker">ZAFE / DOCUMENTATION DESK</p><h1>Create an<br/><em>account.</em></h1><p className="signup-intro">Create a ZAFE administrator account to catalogue records, attach media and manage the living archive.</p><form onSubmit={submit}><label>YOUR NAME<input required value={name} onChange={event=>setName(event.target.value)} placeholder="Name" autoComplete="name"/></label><label>EMAIL ADDRESS<input required type="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder="you@example.com" autoComplete="email"/></label><label>PASSWORD<input required type="password" minLength="8" value={password} onChange={event=>setPassword(event.target.value)} placeholder="At least 8 characters" autoComplete="new-password"/></label><label>CONFIRM PASSWORD<input required type="password" minLength="8" value={confirm} onChange={event=>setConfirm(event.target.value)} placeholder="Repeat your password" autoComplete="new-password"/></label><button disabled={working}>{working?<Loader2/>:<ChevronRight/>}{working?'CREATING ACCOUNT':'CREATE ADMIN ACCOUNT'}</button></form>{message&&<p className={`signup-message ${message.startsWith('Account created')?'success':''}`}>{message.startsWith('Account created')&&<Check/>}{message}</p>}<small className="signup-note">Administrator accounts can access the Documentation Desk and archive operations.</small></div></main>;
}
