import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight,Menu,X,Search,MapPin} from 'lucide-react';
import {supabase} from './lib/supabase';
import AuthPanel from './components/AuthPanel';
import DocumentationDesk from './components/DocumentationDesk';
import SignupPage from './components/SignupPage';
import heroImage from './assets/zafe-hero-zaria.png';
import './styles.css';

const fallbackRecords=[
 {archive_id:'ZAFE-2026-PH-00017',type:'IMAGE',title:'The knowledge sits in the hand',place:'Zaria City',practice:'Embroidery',date:'12 MAY 2026',image:heroImage},
 {archive_id:'ZAFE-2026-OH-00008',type:'VOICE',title:'A city carried in many voices',place:'Tudun Wada',practice:'Oral tradition',date:'18 MAY 2026',quote:'Memory is not behind us. It walks beside us.',image:heroImage},
 {archive_id:'ZAFE-2026-CR-00023',type:'CRAFT',title:'Gold thread / green cloth',place:'Zaria City',practice:'Embroidery',date:'22 MAY 2026',image:heroImage},
 {archive_id:'ZAFE-2026-FM-00004',type:'FILM',title:'Thresholds of Zaria',place:'Zaria City',practice:'Architecture',date:'02 JUN 2026',image:heroImage},
 {archive_id:'ZAFE-2026-TX-00011',type:'TEXT',title:'Notes on inheritance',place:'Samaru',practice:'Research',date:'05 JUN 2026',quote:'A pattern is also an instruction for remembering.',image:heroImage},
 {archive_id:'ZAFE-2026-PP-00006',type:'PEOPLE',title:'The maker and the measure',place:'Sabon Gari',practice:'Cap making',date:'11 JUN 2026',image:heroImage},
 {archive_id:'ZAFE-2026-PL-00003',type:'PLACE',title:'A doorway records the weather',place:'Zaria City',practice:'Architecture',date:'16 JUN 2026',image:heroImage},
 {archive_id:'ZAFE-2026-AU-00009',type:'VOICE',title:'Before the first stitch',place:'Tudun Wada',practice:'Embroidery',date:'21 JUN 2026',quote:'First you learn to watch. Then the hand begins.',image:heroImage},
];
const crafts=['Embroidery','Weaving','Leatherwork','Dyeing','Pottery','Blacksmithing','Cap making'];
const programme=[['02:00','Arrival / exhibition viewing'],['03:00','Keynote: The work of remembering'],['03:45','ZAFE documentary premiere'],['04:30','Panel: Making identity visible'],['05:15','Heritage fashion presentation']];

function Node(){return <span className="zafe-node" aria-hidden="true">◇</span>}
function Header({menu,setMenu}){return <><header className="topbar"><a className="brand" href="/"><span className="mark">Z</span><span>ZAFE<small>ZARIA ART & FASHION EXPO</small></span></a><nav><a href="#edition">2026</a><a href="#archive">Archive</a><a href="#stories">Stories</a><a href="#people">People</a><a href="#about">About</a></nav><div className="head-actions"><a className="signin" href="/desk">Documentation Desk</a><button aria-label="Search"><Search size={17}/></button><button className="menu-btn" onClick={()=>setMenu(!menu)} aria-label="Menu">{menu?<X/>:<Menu/>}</button></div></header>{menu&&<div className="mobile-nav"><a href="#edition">2026</a><a href="#archive">Archive</a><a href="#stories">Stories</a><a href="#people">People</a><a href="/desk">Documentation Desk ↗</a></div>}</>}

function App(){
 const [menu,setMenu]=useState(false),[auth,setAuth]=useState(false),[records,setRecords]=useState(fallbackRecords),[archiveType,setArchiveType]=useState('ALL'),[archiveQuery,setArchiveQuery]=useState(''),[selected,setSelected]=useState(null);
 useEffect(()=>{if(location.pathname.startsWith('/auth'))setAuth(true);if(!supabase)return;supabase.from('records').select('archive_id,type,title,place:places(name),media(url)').eq('status','PUBLISHED').limit(6).then(({data})=>{if(data?.length)setRecords(data.map((r,i)=>({...r,place:r.place?.name||'Zaria',image:r.media?.[0]?.url||fallbackRecords[i%3].image})))})},[]);
 useEffect(()=>{const targets=document.querySelectorAll('main>section, .sheet-item, .craft-list a');const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.14,rootMargin:'0px 0px -7% 0px'});targets.forEach(target=>{target.classList.add('reveal');observer.observe(target)});return()=>observer.disconnect()},[records]);
 const shownRecords=records.filter(r=>(archiveType==='ALL'||r.type===archiveType)&&`${r.title} ${r.archive_id} ${r.place||''} ${r.practice||''}`.toLowerCase().includes(archiveQuery.toLowerCase()));
 if(location.pathname.startsWith('/desk'))return <DocumentationDesk onExit={()=>{location.href='/'}}/>;
 if(location.pathname.startsWith('/signup'))return <SignupPage/>;
 return <><div className="site"><Header menu={menu} setMenu={setMenu}/><main>
  <section className="arrival" id="top"><div className="arrival-thread" aria-hidden="true"><span></span><Node/></div><div className="arrival-copy"><p className="kicker">ZARIA / 2026</p><h1><span>Threads</span><small>of</small><em>Ancestry</em></h1><p>A living archive of art, fashion, memory and making.</p><a href="#question">Follow the thread ↓</a></div><figure className="threshold-frame"><img src={heroImage} alt="Artisan embroidering green cloth in a Zaria architectural courtyard"/><figcaption>ZAFE FIELD RECORD · EMBROIDERY / ZARIA</figcaption></figure><div className="ceremonial-bands" aria-hidden="true"><i/><i/><i/></div></section>
  <section className="question-scene" id="question"><p className="scene-index">01 / THE QUESTION</p><h2>How do the <span>stories</span>, <span>crafts</span>, traditions and identities of our past continue to shape what we <span>create</span> today?</h2><div className="question-thread" aria-hidden="true"><Node/><i/><Node/><i/><Node/></div></section>
  <section className="memory-scene"><div className="scene-label"><Node/> MATERIAL MEMORY <b>ZAFE-2026 / FIELD 04</b></div><div className="memory-grid"><figure className="memory-crop"><img src={heroImage} alt="Close documentary view of embroidery work"/><figcaption>01 / THREAD · NEEDLE · HAND</figcaption></figure><blockquote>“The knowledge sits in the hand before it reaches the cloth.”<cite>FIELD INTERVIEW / ZARIA / 2026</cite></blockquote><div className="field-slip"><small>DOCUMENTATION NOTE</small><strong>PLACE</strong><span>ZARIA CITY</span><strong>PRACTICE</strong><span>TRADITIONAL EMBROIDERY</span><strong>STATUS</strong><span>CATALOGUED <Node/></span></div></div></section>
  <section className="place-scene"><div className="place-copy"><p className="scene-index">02 / PLACE · MEMORY · MAKING</p><h2>Zaria<br/><em>holds.</em></h2><p>Architecture is not a backdrop. It is a record of material, ceremony, climate and the lives moving through it.</p><div className="place-meta"><MapPin size={15}/> 11.0855° N / 7.7199° E</div></div><figure className="place-frame"><img src={heroImage} alt="Architectural threshold and artisan in Zaria"/><figcaption>THRESHOLD STUDY / ZARIA / FIELD 01</figcaption></figure></section>
  <section className="holders" id="people"><div className="holder-portrait"><img src={heroImage} alt="Zaria embroidery artisan at work"/></div><div className="holder-copy"><p className="scene-index">03 / THE KNOWLEDGE HOLDERS</p><h2>The hand<br/>is an <em>archive.</em></h2><div className="holder-path"><span>ARTISAN</span><Node/><span>EMBROIDERY</span><Node/><span>ZARIA</span></div><p>Knowledge moves through demonstration, repetition, correction and memory.</p><a href="#archive"><Node/> FOLLOW THIS THREAD</a></div></section>
  <section className="archive-scene" id="archive"><div className="ghost" aria-hidden="true">ZAFE</div><div className="archive-heading"><div><p className="scene-index">04 / MEMORY MODE</p><h2>The ZAFE<br/><em>Archive</em></h2></div><div className="archive-count"><strong>184</strong><span>CATALOGUED RECORDS</span></div></div><div className="archive-tools"><label><Search size={16}/><input value={archiveQuery} onChange={e=>setArchiveQuery(e.target.value)} placeholder="Search title, ID, place or practice"/></label><span>{shownRecords.length} RECORDS SHOWN</span></div><div className="archive-types"><button className={archiveType==='ALL'?'active':''} onClick={()=>setArchiveType('ALL')}><Node/>ALL</button>{['IMAGE','FILM','VOICE','TEXT','PEOPLE','PLACE'].map(x=><button className={archiveType===x?'active':''} key={x} onClick={()=>setArchiveType(x)}><Node/>{x}</button>)}</div><div className="archive-layout"><div className="contact-sheet" id="records">{shownRecords.map((r,i)=><article key={r.archive_id} className={`${i===0?'sheet-item featured':'sheet-item'} ${r.quote?'text-record':''}`} onClick={()=>setSelected(r)}>{r.quote?<blockquote>“{r.quote}”<cite>{r.archive_id}</cite></blockquote>:<figure><img src={r.image} alt=""/><span>{String(i+1).padStart(2,'0')}</span><b>{r.type}</b></figure>}<div><small>{r.archive_id}</small><h3>{r.title}</h3><dl><div><dt>PLACE</dt><dd>{r.place||'Zaria'}</dd></div><div><dt>PRACTICE</dt><dd>{r.practice||'Documentation'}</dd></div><div><dt>DATE</dt><dd>{r.date||'2026'}</dd></div></dl><button><Node/> OPEN CATALOGUE RECORD</button></div></article>)}</div><aside className={`archive-preview ${selected?'open':''}`}>{selected?<><button className="preview-close" onClick={()=>setSelected(null)}>CLOSE ×</button><small>{selected.archive_id}</small><figure><img src={selected.image} alt=""/></figure><p>{selected.type} · {selected.date||'2026'}</p><h3>{selected.title}</h3><dl><dt>PLACE</dt><dd>{selected.place}</dd><dt>PRACTICE</dt><dd>{selected.practice||'Documentation'}</dd></dl><a href={`/records/${selected.archive_id}`}><Node/> VIEW FULL RECORD <ArrowUpRight size={14}/></a></>:<><Node/><p>SELECT A RECORD TO OPEN THE ARCHIVAL PREVIEW.</p></>}</aside></div><a className="structural-link" href="/archive">ENTER THE FULL ARCHIVE <ArrowUpRight size={16}/></a></section>
  <section className="craft-scene"><p className="scene-index">05 / PRACTICE-DRIVEN NAVIGATION</p><h2>Craft index</h2><div className="craft-list">{crafts.map((c,i)=><a href={`/archive?practice=${c.toLowerCase()}`} key={c}><span>0{i+1}</span><strong>{c}</strong><i/><Node/></a>)}</div></section>
  <section className="interpretation"><div className="interpretation-copy"><p className="scene-index">06 / CONTEMPORARY INTERPRETATION</p><h2>Inheritance<br/>is not <em>still.</em></h2><div className="lineage"><span>HERITAGE</span><i/><Node/><span>MATERIAL</span><i/><Node/><span>INTERPRETATION</span></div></div><figure><img src={heroImage} alt="Contemporary green textile rooted in Zaria embroidery practice"/><figcaption>SOURCE PRACTICE / EMBROIDERY · MATERIAL / THREAD · PLACE / ZARIA</figcaption></figure></section>
  <section className="field-scene" id="stories"><div className="scene-label"><Node/> FROM THE FIELD <b>RESEARCH IN PROGRESS</b></div><div className="field-grid">{[1,2,3,4,5,6].map((n)=><figure key={n}><img src={heroImage} alt=""/><span>{String(n).padStart(2,'0')}</span></figure>)}</div><aside><small>FIELD NOTE / 08.2026</small><blockquote>Observe the threshold. Record the hand. Ask where the pattern began.</blockquote><p>ZARIA CITY · INTERVIEW TRANSCRIPTION 62%</p></aside></section>
  <section className="programme" id="edition"><p className="scene-index">07 / ZAFE 2026 PROGRAMME</p><h2>A day along<br/><em>the thread.</em></h2><div className="timeline">{programme.map(([time,title])=><div className="time" key={time}><span>{time}</span><Node/><strong>{title}</strong></div>)}</div></section>
  <section className="closing" id="about"><div className="closing-thread" aria-hidden="true"><i/><Node/><i/></div><p>ZARIA ART & FASHION EXPO</p><h2>Research.<br/><em>Remember.</em><br/>Reimagine.</h2><span>Culture survives when it is documented, practised and passed on.</span></section>
 </main><footer><div className="brand"><span className="mark">Z</span><span>ZAFE<small>ZARIA ART & FASHION EXPO</small></span></div><div>AHMADU BELLO UNIVERSITY · ZARIA · 2026</div><a href="#top">BACK TO TOP ↑</a></footer></div>{auth&&<AuthPanel onClose={()=>setAuth(false)}/>}</>;
}
createRoot(document.getElementById('root')).render(<App/>);
